### PR TITLE
#251 Window error in NodeJS

### LINKED ISSUE #251: 1.4.0 broken in node.js
Looks like somehow a dependency on 'window' snuck in.

~/tmp/fp  $ npm install firepad@1.4.0
firepad@1.4.0 node_modules/firepad
├── jsdom@9.2.1 (acorn-globals@1.0.9, webidl-conversions@3.0.1, array-equal@1.0.0, sax@1.2.1, abab@1.0.3, xml-name-validator@2.0.1, symbol-tree@3.1.4, tough-cookie@2.2.2, nwmatcher@1.3.8, cssom@0.3.1, iconv-lite@0.4.13, parse5@1.5.1, acorn@2.7.0, whatwg-url@3.0.0, escodegen@1.8.0, request@2.72.0, cssstyle@0.2.36)
└── firebase@3.0.5 (rsvp@3.2.1, faye-websocket@0.9.3, jsonwebtoken@5.7.0)

~/tmp/fp  $ node -e "require('firepad')"
/Users/mikelehen/tmp/fp/node_modules/firepad/dist/firepad.min.js:13
!function(a,b,c){"undefined"!=typeof module&&module.exports?module.exports=b():"function"==typeof c.define&&c.define.amd?define(b):c[a]=b()}("Firepad",function(){var a=a||{};a.utils={},a.utils.makeEventEmitter=function(a,b){a.prototype.allowedEvents_=b,a.prototype.on=function(a,b,c){this.validateEventType_(a),this.eventListeners_=this.eventListeners_||{},this.eventListeners_[a]=this.eventListeners_[a]||[],this.eventListeners_[a].push({callback:b,context:c})},a.prototype.off=function(a,b){this.validateEventType_(a),this.eventListeners_=this.eventListeners_||{};for(var c=this.eventListeners_[a]||[],d=0;d<c.length;d++)if(c[d].callback===b)return void c.splice(d,1)},a.prototype.trigger=function(a){this.eventListeners_=this.eventListeners_||{};for(var b=this.eventListeners_[a]||[],c=0;c<b.length;c++)b[c].callback.apply(b[c].context,Array.prototype.slice.call(arguments,1))},a.prototype.validateEventType_=function(a){if(this.allowedEvents_){for(va

ReferenceError: window is not defined
    at /Users/mikelehen/tmp/fp/node_modules/firepad/dist/firepad.min.js:13:17964
    at /Users/mikelehen/tmp/fp/node_modules/firepad/dist/firepad.min.js:13:23320
    at a (/Users/mikelehen/tmp/fp/node_modules/firepad/dist/firepad.min.js:13:76)
    at Object.<anonymous> (/Users/mikelehen/tmp/fp/node_modules/firepad/dist/firepad.min.js:13:141)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

### PR DESCRIPTION
**Pull request by prescottprue**
### Description
* Fixes #251: Window Error when using NodeJS

### CODE REVIEW

**Comment by prescottprue** [comment]
I signed it!

**Comment by prescottprue** [comment]
Tests are still not passing. Planning on looking into it tomorrow.

**Comment by mikelehen** [comment]
Thanks! I think we still need to check for firebase being defined before calling require('firebase)'.  Hopefully that fixes the tests, though they've also been a bit flaky in travis. :-/

File: lib/firebase-adapter.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ var firepad = firepad || { };
 
 firepad.FirebaseAdapter = (function (global) {
 
-  if (window.firebase === undefined && typeof require === 'function' && typeof Firebase !== 'function') {
+  if (typeof require === 'function' && typeof Firebase !== 'function') {
```
Comment (prescottprue) [inline lib/firebase-adapter.js]: Added this back in. Also, somewhat unrelated, but it looked like the tests were just failing due to Jasmine timeouts. I have been playing around with modifying that timeout so test will pass.

File: test/specs/integration.spec.js [hunk 2]
```diff
@@ -50,6 +50,7 @@ describe('Integration tests', function() {
   beforeEach(function(done) {
     // Make sure we're connected to Firebase.  This can take a while on slow
     // connections.
+    jasmine.DEFAULT_TIMEOUT_INTERVAL = 180000;
```
Comment (mikelehen) [inline test/specs/integration.spec.js]: I don't want to set this too high, since when there is a real bug causing an async test not to finish, it'll now take 3 minutes for the test to fail!  Were you able to reproduce the timeouts yourself?  I'm fine with e.g. doubling the timeout (not sure what the default is though) if we think it'll make the tests more reliable, but 3 minutes is probably too far. :-)

Comment (prescottprue) [inline test/specs/integration.spec.js]: @mikelehen I was finally able to get the tests to pass on travis by passing only added timeout only to tests that were timeing out. I agree with not wanting to make it wait for too long on a failure, so I made sure to only put the timeouts where necessary (it seems like the `beforeEach` needed it more than anything else)

Totally open to not modifying timeout amounts, but this is literally the only way I was able to get it to pass on travis.

**Comment by prescottprue** [comment]
Apologies for having to rerun travis over and over, I was testing solving the timeout issue.

It seems like timeout is mostly necessary on the [beforeEach](https://github.com/firebase/firepad/blob/master/test/specs/integration.spec.js#L50-L62) for the integration tests.

File: test/specs/integration.spec.js [hunk 3]
```diff
@@ -108,7 +110,7 @@ describe('Integration tests', function() {
       firepad1.setText('lorem ipsum');
       step(25);
     });
-  });
+  }, 6000000);
```
Comment (mikelehen) [inline test/specs/integration.spec.js]: 6000000ms = 6000s = 100min ...   surely that's way overkill?

Comment (prescottprue) [inline test/specs/integration.spec.js]: Yup it was way overkill. I mostly wanted to see Travis pass then didn't come back and adjust. It is set to 5 mins now and is a variable so all extended timeouts are the same length.

**Comment by mikelehen** [comment]
Merged in.  Thanks!
